modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="oddly_specific_bars"
version="1.0.0"
displayName="Oddly specific bars"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.oddly_specific_bars]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration